version: '3'
services:
  parrot:
    build:
      context: ../parrot/
    ports:
     - 514:514/udp
     - 8080:8080
  log-generator:
    build:
      context: ../parrot/
    entrypoint: [ "/log-generator"]
  log-generator2:
    build:
      context: ../parrot/
    entrypoint: [ "/log-generator"]
  log-generator3:
    build:
      context: ../parrot/
    entrypoint: [ "/log-generator"]
  log-generator4:
    build:
      context: ../parrot/
    entrypoint: [ "/log-generator"]
